export const seoContentStaticPage = {
  home: {
    title: 'Home',
    description: 'Welcome to our website. Discover amazing products and services.',
    type: 'website',
    siteName: 'Your Website Name',
    url: 'https://yourwebsite.com',
    image: 'https://yourwebsite.com/images/home.jpg',
    twitter: '@yourtwitter',
    facebook: 'yourfacebook',
    robots: 'index, follow',
    locale: 'en_US',
    date: '2024-03-21',
    modified: '2024-03-21'
  },
  login: {
    title: 'Login',
    description: 'Login to access your account and enjoy personalized features.',
    type: 'website',
    siteName: 'Your Website Name',
    url: 'https://yourwebsite.com/login',
    image: 'https://yourwebsite.com/images/login.jpg',
    twitter: '@yourtwitter',
    facebook: 'yourfacebook',
    robots: 'noindex, nofollow',
    locale: 'en_US',
    date: '2024-03-21',
    modified: '2024-03-21'
  },
  register: {
    title: 'Register',
    description: 'Create a new account to access exclusive content and services.',
    type: 'website',
    siteName: 'Your Website Name',
    url: 'https://yourwebsite.com/register',
    image: 'https://yourwebsite.com/images/register.jpg',
    twitter: '@yourtwitter',
    facebook: 'yourfacebook',
    robots: 'noindex, nofollow',
    locale: 'en_US',
    date: '2024-03-21',
    modified: '2024-03-21'
  },
  about_us: {
    title: 'About Us',
    description: 'Learn more about our company and mission.',
    type: 'website',
    siteName: 'Your Website Name',
    url: 'https://yourwebsite.com/about',
    image: 'https://yourwebsite.com/images/about.jpg',
    twitter: '@yourtwitter',
    facebook: 'yourfacebook',
    robots: 'index, follow',
    locale: 'en_US',
    date: '2024-03-21',
    modified: '2024-03-21'
  },
  contact: {
    title: 'Contact',
    description: "Get in touch with us. We're here to help.",
    type: 'website',
    siteName: 'Your Website Name',
    url: 'https://yourwebsite.com/contact',
    image: 'https://yourwebsite.com/images/contact.jpg',
    twitter: '@yourtwitter',
    facebook: 'yourfacebook',
    robots: 'index, follow',
    locale: 'en_US',
    date: '2024-03-21',
    modified: '2024-03-21'
  }
}
